### PR TITLE
Abduallah-sudocode 

### PR DESCRIPTION
**Pull request by abduallahB**

### CODE REVIEW

**Comment by halitbatur** [comment]
@abduallahB could u write ur actual pesudo code and no need to nest it inside a new dir just adding the file to pesudo-code dir is enough

**Comment by abduallahB** [comment]
Done ,could you please confirm

**Comment by halitbatur** [comment]
@abduallahB I see a problem now with class 1 u need to create a folder for your exercise instead of putting the files in class-1 right away

**Comment by abduallahB** [comment]
Yes, my friend Rahaf submit it in the right place

**Pull request closed without merging**
