### PR TITLE
Abduallah-Zakaria-Belal-Deniz-class-4-JS-basics

### PR DESCRIPTION
**Pull request by abduallahB**

### CODE REVIEW

**Comment by halitbatur** [comment]
@abduallahB the PR name is not correct could u please fix it ?

**Comment by abduallahB** [comment]
do you mean this : class-4 challenge1-2   ? 
could you please tell me what is the coorect name

**Comment by halitbatur** [comment]
@abduallahB it should be yourName-yourPartnerName-class-4-JS-basics

**Comment by abduallahB** [comment]
but I create a files insid this file for each challenge with my partner nams

**Comment by halitbatur** [comment]
@abduallahB Im talking about the PR title

**Comment by abduallahB** [comment]
Okay could you please check now !

**Comment by halitbatur** [comment]
@abduallahB i see a small problem with the directory names for each exercise there shouldn't be spaces used for the directory names

**Comment by abduallahB** [comment]
there is no space between our nams of each exercise I add ( - ) 
ex: abduallah-zekaria

**Comment by halitbatur** [comment]
@abduallahB please read my comment carefully and take a look at the "directory names"

**Comment by halitbatur** [comment]
first directory naming mistake:
image
second mistake:
image

**Comment by halitbatur** [comment]
as you can see spaces were used in naming these directories please fix them and push the changes

**Comment by abduallahB** [comment]
I removed the files and added them again with correct nams but when I mad push it is give me this 
 **Everything up-to-date**
is that correct ?

**Comment by abduallahB** [comment]
could you please check now if it is fixed

**Comment by halitbatur** [comment]
@abduallahB This folder still have space in the end of the name 
image

**Comment by abduallahB** [comment]
yes I trid to change it but dose not work with I am guss I am doing in the wrong place

**Comment by abduallahB** [comment]
Hi halit now I think the problem fixed could you please take a look and accepted

**Comment by halitbatur** [comment]
@abduallahB LGTM

**Pull request merged**
